package org.openntf.drapi.api.options;

import java.util.ArrayList;
import java.util.List;
import org.openntf.drapi.util.Parameter;

/**
 * Optional query parameters for the "retrieve a document" operation of the HCL Domino REST API ({@code GET /document/{unid}}, operation
 * id {@code getDocument}), which retrieves a given document at its appropriate mode.
 * <p>
 * Every setter corresponds to one query-string parameter of that operation; the parameter descriptions below are taken from the Domino
 * REST API basis OpenAPI schema (version 1.42.6). A {@code null} field means the parameter is omitted from the request and the server
 * default applies. The document unid and the required {@code dataSource} (scope) parameter are supplied separately by the calling API
 * method and are not represented here.
 * <p>
 * Instances are mutable and not thread-safe. Obtain one through {@link #create()} and configure it fluently.
 * <p>
 * <i>Auto-generated by Claude Code (Sonnet 5) based on HCL Domino Rest API - OpenApi specification 1.42.6</i>
 */
public final class DocumentsGetOptions {

    public static final String PARAM_MARK_UNREAD = "markUnread";
    public static final String PARAM_MODE = "mode";
    public static final String PARAM_META = "meta";
    public static final String PARAM_RICH_TEXT_AS = "richTextAs";
    public static final String PARAM_MARK_READ = "markRead";

    private String mode = null;
    private Boolean meta = null;
    private RichTextAs richTextAs = null;
    private Boolean markRead = null;
    private Boolean markUnread = null;

    private DocumentsGetOptions() {
    }

    /**
     * Creates an empty option set in which every parameter is unset.
     *
     * @return a new, mutable {@code DocumentsGetOptions}
     */
    public static DocumentsGetOptions create() {
        return new DocumentsGetOptions();
    }

    /**
     * Sets the {@code mode} query parameter: the mode to perform the document access in. Defaults to {@code default} when missing. The
     * value must be all lowercase with no spaces, using letters and numbers only.
     *
     * @param mode the document access mode name
     * @return this option set, for chaining
     */
    public DocumentsGetOptions mode(String mode) {
        this.mode = mode;
        return this;
    }

    /**
     * Sets the {@code meta} query parameter. When set to {@code false}, all metadata JSON items on the top level of an object are
     * suppressed. The server default is {@code true}.
     *
     * @param meta whether to include top-level metadata items
     * @return this option set, for chaining
     */
    public DocumentsGetOptions meta(Boolean meta) {
        this.meta = meta;
        return this;
    }

    /**
     * Sets the {@code richTextAs} query parameter: the format in which rich text fields are returned. The default when unspecified is
     * {@code html}.
     *
     * @param richTextAs the rich text representation to request
     * @return this option set, for chaining
     */
    public DocumentsGetOptions richTextAs(RichTextAs richTextAs) {
        this.richTextAs = richTextAs;
        return this;
    }

    /**
     * Sets the {@code markRead} query parameter: mark the document as read by the current user when the operation completes.
     *
     * @param markRead whether to mark the document as read
     * @return this option set, for chaining
     */
    public DocumentsGetOptions markRead(Boolean markRead) {
        this.markRead = markRead;
        return this;
    }

    /**
     * Sets the {@code markUnread} query parameter: mark the document as unread by the current user when the operation completes.
     *
     * @param markUnread whether to mark the document as unread
     * @return this option set, for chaining
     */
    public DocumentsGetOptions markUnread(Boolean markUnread) {
        this.markUnread = markUnread;
        return this;
    }

    /**
     * Returns the configured {@code mode}, or {@code null} if unset.
     *
     * @return the document access mode, or {@code null}
     */
    public String mode() {
        return mode;
    }

    /**
     * Returns the configured {@code meta} flag, or {@code null} if unset.
     *
     * @return whether top-level metadata is included, or {@code null}
     */
    public Boolean meta() {
        return meta;
    }

    /**
     * Returns the configured {@code richTextAs} representation, or {@code null} if unset.
     *
     * @return the rich text representation, or {@code null}
     */
    public RichTextAs richTextAs() {
        return richTextAs;
    }

    /**
     * Returns the configured {@code markRead} flag, or {@code null} if unset.
     *
     * @return whether the document is marked as read, or {@code null}
     */
    public Boolean markRead() {
        return markRead;
    }

    /**
     * Returns the configured {@code markUnread} flag, or {@code null} if unset.
     *
     * @return whether the document is marked as unread, or {@code null}
     */
    public Boolean markUnread() {
        return markUnread;
    }

    /**
     * Returns a list of {@link Parameter} objects representing the configured query parameters. Parameters left unset are omitted from
     * the list, so the server defaults take effect for them.
     *
     * @return a list of {@link Parameter} objects representing the configured query parameters
     */
    public List<Parameter> toParameterList() {
        List<Parameter> params = new ArrayList<>();

        if (mode != null) {
            params.add(new Parameter(PARAM_MODE, mode));
        }
        if (meta != null) {
            params.add(new Parameter(PARAM_META, meta.toString()));
        }
        if (richTextAs != null) {
            params.add(new Parameter(PARAM_RICH_TEXT_AS, richTextAs.value()));
        }
        if (markRead != null) {
            params.add(new Parameter(PARAM_MARK_READ, markRead.toString()));
        }
        if (markUnread != null) {
            params.add(new Parameter(PARAM_MARK_UNREAD, markUnread.toString()));
        }

        return params;
    }

}
