/*
 * Copyright (c) 2026 Serdar Basegmez
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openntf.drapi.api.options;

import java.util.ArrayList;
import java.util.List;
import org.openntf.drapi.util.Parameter;

/**
 * Optional query parameters for the "fetch view entries" operation of the HCL Domino REST API ({@code GET /lists/{name}}, operation id
 * {@code fetchViewEntries}), which pulls in view or folder data for a list.
 * <p>
 * Every setter corresponds to one query-string parameter of that operation; the parameter descriptions below are taken from the Domino
 * REST API basis OpenAPI schema (version 1.42.6). A {@code null} field means the parameter is omitted from the request and the server
 * default applies. The list name and the required {@code dataSource} (scope) parameter are supplied separately by the calling API
 * method and are not represented here.
 * <p>
 * Instances are mutable and not thread-safe. Obtain one through {@link #create()} and configure it fluently.
 * <p>
 * <i>Boilerplate code and Javadoc are generated by Claude Code (Sonnet 5) based on HCL Domino Rest API - OpenApi specs 1.42.6</i>
 */
public final class ListsGetOptions {

    public static final String PARAM_MODE = "mode";
    public static final String PARAM_META = "meta";
    public static final String PARAM_STARTS_WITH = "startsWith";
    public static final String PARAM_META_ADDITIONAL = "metaAdditional";
    public static final String PARAM_CATEGORY = "category";
    public static final String PARAM_COLUMN = "column";
    public static final String PARAM_DISTINCT_DOCUMENTS = "distinctDocuments";
    public static final String PARAM_FT_SEARCH_QUERY = "ftSearchQuery";
    public static final String PARAM_COUNT = "count";
    public static final String PARAM_START_KEY = "startKey";
    public static final String PARAM_UNTIL_KEY = "untilKey";
    public static final String PARAM_UNREAD_ONLY = "unreadOnly";
    public static final String PARAM_KEY_ALLOW_PARTIAL = "keyAllowPartial";
    public static final String PARAM_DOCUMENTS = "documents";
    public static final String PARAM_DIRECTION = "direction";
    public static final String PARAM_RICH_TEXT_AS = "richTextAs";
    public static final String PARAM_KEY_TYPE = "keyType";
    public static final String PARAM_KEY = "key";
    public static final String PARAM_SCOPE = "scope";
    public static final String PARAM_MARK_READ = "markRead";
    public static final String PARAM_MARK_UNREAD = "markUnread";
    public static final String PARAM_INCLUDE_EMPTY_ROWS = "includeEmptyRows";
    public static final String PARAM_START = "start";

    private String mode = null;
    private Boolean meta = null;
    private String startsWith = null;
    private Boolean metaAdditional = null;
    private List<String> category = null;
    private String column = null;
    private Boolean distinctDocuments = null;
    private String ftSearchQuery = null;
    private Integer count = null;
    private String startKey = null;
    private String untilKey = null;
    private Boolean unreadOnly = null;
    private Boolean keyAllowPartial = null;
    private Boolean documents = null;
    private Direction direction = null;
    private RichTextAs richTextAs = null;
    private KeyType keyType = null;
    private List<String> key = null;
    private QueryScope scope = null;
    private Boolean markRead = null;
    private Boolean markUnread = null;
    private Boolean includeEmptyRows = null;
    private Integer start = null;

    private ListsGetOptions() {
    }

    /**
     * Creates an empty option set in which every parameter is unset.
     *
     * @return a new, mutable {@code ListsGetOptions}
     */
    public static ListsGetOptions create() {
        return new ListsGetOptions();
    }

    /**
     * Sets the {@code mode} query parameter: the document mode to retrieve the documents with. Every form can define multiple modes,
     * each potentially different from the others, and the current logged-in user must have access to the mode requested.
     *
     * @param mode the document mode name
     * @return this option set, for chaining
     */
    public ListsGetOptions mode(String mode) {
        this.mode = mode;
        return this;
    }

    /**
     * Sets the {@code meta} query parameter. When set to {@code false}, all metadata JSON items on the top level of an object are
     * suppressed. The server default is {@code true}.
     *
     * @param meta whether to include top-level metadata items
     * @return this option set, for chaining
     */
    public ListsGetOptions meta(Boolean meta) {
        this.meta = meta;
        return this;
    }

    /**
     * Sets the {@code startsWith} query parameter: a character combination used to perform a partial match that identifies a starting
     * point. The combination is applied to the {@code column} and {@code direction} passed in the query string. This cannot be combined
     * with {@link #key(List) key}; you cannot filter on keys and on a {@code startsWith} within that key.
     *
     * @param startsWith the leading character combination to match
     * @return this option set, for chaining
     */
    public ListsGetOptions startsWith(String startsWith) {
        this.startsWith = startsWith;
        return this;
    }

    /**
     * Sets the {@code metaAdditional} query parameter: request additional metadata that is not included in the view. This can carry a
     * slight performance cost, so use it only if necessary.
     *
     * @param metaAdditional whether to include the additional metadata
     * @return this option set, for chaining
     */
    public ListsGetOptions metaAdditional(Boolean metaAdditional) {
        this.metaAdditional = metaAdditional;
        return this;
    }

    /**
     * Sets the {@code category} query parameter: the category or categories to restrict view queries to. The supplied list is
     * defensively copied.
     *
     * @param category the categories to restrict the query to
     * @return this option set, for chaining
     */
    public ListsGetOptions category(List<String> category) {
        this.category = List.copyOf(category);
        return this;
    }

    /**
     * Convenience overload of {@link #category(List)} accepting the categories as varargs.
     *
     * @param categories the categories to restrict the query to
     * @return this option set, for chaining
     */
    public ListsGetOptions category(String... categories) {
        this.category = List.of(categories);
        return this;
    }

    /**
     * Sets the {@code column} query parameter: the column to use for alternative sorting. This requires the list to be designed for
     * indexing on that column.
     *
     * @param column the programmatic column name to sort on
     * @return this option set, for chaining
     */
    public ListsGetOptions column(String column) {
        this.column = column;
        return this;
    }

    /**
     * Sets the {@code distinctDocuments} query parameter: when {@link #documents(Boolean) documents} is {@code true}, controls whether
     * only distinct documents are retrieved for documents that appear multiple times in the list.
     *
     * @param distinctDocuments whether to collapse duplicate documents
     * @return this option set, for chaining
     */
    public ListsGetOptions distinctDocuments(Boolean distinctDocuments) {
        this.distinctDocuments = distinctDocuments;
        return this;
    }

    /**
     * Sets the {@code ftSearchQuery} query parameter: a full-text search query used to filter the contents of the list.
     *
     * @param ftSearchQuery the full-text search query
     * @return this option set, for chaining
     */
    public ListsGetOptions ftSearchQuery(String ftSearchQuery) {
        this.ftSearchQuery = ftSearchQuery;
        return this;
    }

    /**
     * Sets the {@code count} query parameter: how many entries to return. The server default is {@code 1000}; pass {@code -1} to return
     * all entries (up to {@code Integer.MAX_VALUE}).
     *
     * @param count the maximum number of entries to return
     * @return this option set, for chaining
     */
    public ListsGetOptions count(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * Sets the {@code startKey} query parameter: the key value of the first entry to retrieve. It is treated as a greater-than-or-equal
     * lookup.
     *
     * @param startKey the first key value to include
     * @return this option set, for chaining
     */
    public ListsGetOptions startKey(String startKey) {
        this.startKey = startKey;
        return this;
    }

    /**
     * Sets the {@code untilKey} query parameter: the key value at which traversal stops when combined with
     * {@link #startKey(String) startKey}. It is treated as a greater-than-or-equal lookup and represents the first value that is not
     * returned.
     *
     * @param untilKey the first key value to exclude
     * @return this option set, for chaining
     */
    public ListsGetOptions untilKey(String untilKey) {
        this.untilKey = untilKey;
        return this;
    }

    /**
     * Convenience method that sets both {@link #startKey(String) startKey} and {@link #untilKey(String) untilKey} to define a half-open
     * key range: entries from {@code startKey} inclusive up to, but not including, {@code untilKey}.
     *
     * @param startKey the first key value to include
     * @param untilKey the first key value to exclude
     * @return this option set, for chaining
     */
    public ListsGetOptions betweenKeys(String startKey, String untilKey) {
        this.startKey = startKey;
        this.untilKey = untilKey;
        return this;
    }

    /**
     * Sets the {@code unreadOnly} query parameter: retrieve only unread entries. This cannot be combined with {@code documents=true},
     * {@code documentsOnly=true}, or any other means of selecting or querying documents.
     *
     * @param unreadOnly whether to restrict the result to unread entries
     * @return this option set, for chaining
     */
    public ListsGetOptions unreadOnly(Boolean unreadOnly) {
        this.unreadOnly = unreadOnly;
        return this;
    }

    /**
     * Sets the {@code keyAllowPartial} query parameter: allow selection by partial key. The default is {@code false}, meaning the key
     * match must be exact.
     *
     * @param keyAllowPartial whether partial key matches are accepted
     * @return this option set, for chaining
     */
    public ListsGetOptions keyAllowPartial(Boolean keyAllowPartial) {
        this.keyAllowPartial = keyAllowPartial;
        return this;
    }

    /**
     * Sets the {@code documents} query parameter: whether the query returns documents instead of view entries.
     *
     * @param documents whether to return documents rather than view entries
     * @return this option set, for chaining
     */
    public ListsGetOptions documents(Boolean documents) {
        this.documents = documents;
        return this;
    }

    /**
     * Sets the {@code direction} query parameter: the direction for alternative sorting. This is ignored unless
     * {@link #column(String) column} is also supplied, and it requires the list to be designed for indexing on that column in the
     * desired direction. Defaults to ascending when {@code column} is set.
     *
     * @param direction the sort direction
     * @return this option set, for chaining
     */
    public ListsGetOptions direction(Direction direction) {
        this.direction = direction;
        return this;
    }

    /**
     * Convenience method equivalent to {@link #direction(Direction) direction(Direction.ASCENDING)}.
     *
     * @return this option set, for chaining
     */
    public ListsGetOptions ascending() {
        this.direction = Direction.ASCENDING;
        return this;
    }

    /**
     * Convenience method equivalent to {@link #direction(Direction) direction(Direction.DESCENDING)}.
     *
     * @return this option set, for chaining
     */
    public ListsGetOptions descending() {
        this.direction = Direction.DESCENDING;
        return this;
    }

    /**
     * Sets the {@code richTextAs} query parameter: the format in which rich text fields are returned when retrieving documents instead
     * of view entries. The default when unspecified is {@code mime}.
     *
     * @param richTextAs the rich text representation to request
     * @return this option set, for chaining
     */
    public ListsGetOptions richTextAs(RichTextAs richTextAs) {
        this.richTextAs = richTextAs;
        return this;
    }

    /**
     * Sets the {@code keyType} query parameter: the type of the keys used in {@link #startKey(String) startKey} and
     * {@link #untilKey(String) untilKey}.
     *
     * @param keyType the key type
     * @return this option set, for chaining
     */
    public ListsGetOptions keyType(KeyType keyType) {
        this.keyType = keyType;
        return this;
    }

    /**
     * Sets the {@code key} query parameter: for categorized or sorted lists, limits the returned values to entries matching the given
     * key or keys. The keys must be given in the same order as the sorted columns from left to right; unsorted columns are ignored. The
     * supplied list is defensively copied.
     *
     * @param key the ordered key values to match
     * @return this option set, for chaining
     */
    public ListsGetOptions key(List<String> key) {
        this.key = List.copyOf(key);
        return this;
    }

    /**
     * Convenience overload of {@link #key(List)} that also sets {@link #keyType(KeyType) keyType} and accepts the key values as
     * varargs.
     *
     * @param keyType the key type
     * @param keys    the ordered key values to match
     * @return this option set, for chaining
     */
    public ListsGetOptions key(KeyType keyType, String... keys) {
        this.keyType = keyType;
        this.key = List.of(keys);
        return this;
    }

    /**
     * Sets the {@code scope} query parameter: what the view returns, namely document entries, category names, or all of them.
     *
     * @param scope the query scope
     * @return this option set, for chaining
     */
    public ListsGetOptions scope(QueryScope scope) {
        this.scope = scope;
        return this;
    }

    /**
     * Sets the {@code markRead} query parameter: when retrieving documents instead of view entries, mark them as read by the current
     * user after retrieval.
     *
     * @param markRead whether to mark retrieved documents as read
     * @return this option set, for chaining
     */
    public ListsGetOptions markRead(Boolean markRead) {
        this.markRead = markRead;
        return this;
    }

    /**
     * Sets the {@code markUnread} query parameter: when retrieving documents instead of view entries, mark them as unread by the
     * current user after retrieval.
     *
     * @param markUnread whether to mark retrieved documents as unread
     * @return this option set, for chaining
     */
    public ListsGetOptions markUnread(Boolean markUnread) {
        this.markUnread = markUnread;
        return this;
    }

    /**
     * Sets the {@code includeEmptyRows} query parameter: whether to include rows with no column content in the result array.
     *
     * @param includeEmptyRows whether empty rows are included
     * @return this option set, for chaining
     */
    public ListsGetOptions includeEmptyRows(Boolean includeEmptyRows) {
        this.includeEmptyRows = includeEmptyRows;
        return this;
    }

    /**
     * Sets the {@code start} query parameter: the zero-based index of the first entry to return. The server default is {@code 0}.
     *
     * @param start the zero-based index of the first entry to return
     * @return this option set, for chaining
     */
    public ListsGetOptions start(Integer start) {
        this.start = start;
        return this;
    }

    /**
     * Returns the configured {@code mode}, or {@code null} if unset.
     *
     * @return the document mode, or {@code null}
     */
    public String mode() {
        return mode;
    }

    /**
     * Returns the configured {@code meta} flag, or {@code null} if unset.
     *
     * @return whether top-level metadata is included, or {@code null}
     */
    public Boolean meta() {
        return meta;
    }

    /**
     * Returns the configured {@code startsWith} prefix, or {@code null} if unset.
     *
     * @return the leading character combination to match, or {@code null}
     */
    public String startsWith() {
        return startsWith;
    }

    /**
     * Returns the configured {@code metaAdditional} flag, or {@code null} if unset.
     *
     * @return whether additional metadata is requested, or {@code null}
     */
    public Boolean metaAdditional() {
        return metaAdditional;
    }

    /**
     * Returns the configured {@code category} list, or {@code null} if unset.
     *
     * @return the categories to restrict the query to, or {@code null}
     */
    public List<String> category() {
        return category;
    }

    /**
     * Returns the configured {@code column}, or {@code null} if unset.
     *
     * @return the alternative sort column, or {@code null}
     */
    public String column() {
        return column;
    }

    /**
     * Returns the configured {@code distinctDocuments} flag, or {@code null} if unset.
     *
     * @return whether duplicate documents are collapsed, or {@code null}
     */
    public Boolean distinctDocuments() {
        return distinctDocuments;
    }

    /**
     * Returns the configured {@code ftSearchQuery}, or {@code null} if unset.
     *
     * @return the full-text search query, or {@code null}
     */
    public String ftSearchQuery() {
        return ftSearchQuery;
    }

    /**
     * Returns the configured {@code count}, or {@code null} if unset.
     *
     * @return the maximum number of entries to return, or {@code null}
     */
    public Integer count() {
        return count;
    }

    /**
     * Returns the configured {@code startKey}, or {@code null} if unset.
     *
     * @return the first key value to include, or {@code null}
     */
    public String startKey() {
        return startKey;
    }

    /**
     * Returns the configured {@code untilKey}, or {@code null} if unset.
     *
     * @return the first key value to exclude, or {@code null}
     */
    public String untilKey() {
        return untilKey;
    }

    /**
     * Returns the configured {@code unreadOnly} flag, or {@code null} if unset.
     *
     * @return whether the result is restricted to unread entries, or {@code null}
     */
    public Boolean unreadOnly() {
        return unreadOnly;
    }

    /**
     * Returns the configured {@code keyAllowPartial} flag, or {@code null} if unset.
     *
     * @return whether partial key matches are accepted, or {@code null}
     */
    public Boolean keyAllowPartial() {
        return keyAllowPartial;
    }

    /**
     * Returns the configured {@code documents} flag, or {@code null} if unset.
     *
     * @return whether documents are returned instead of view entries, or {@code null}
     */
    public Boolean documents() {
        return documents;
    }

    /**
     * Returns the configured {@code direction}, or {@code null} if unset.
     *
     * @return the sort direction, or {@code null}
     */
    public Direction direction() {
        return direction;
    }

    /**
     * Returns the configured {@code richTextAs} representation, or {@code null} if unset.
     *
     * @return the rich text representation, or {@code null}
     */
    public RichTextAs richTextAs() {
        return richTextAs;
    }

    /**
     * Returns the configured {@code keyType}, or {@code null} if unset.
     *
     * @return the key type, or {@code null}
     */
    public KeyType keyType() {
        return keyType;
    }

    /**
     * Returns the configured {@code key} list, or {@code null} if unset.
     *
     * @return the ordered key values to match, or {@code null}
     */
    public List<String> key() {
        return key;
    }

    /**
     * Returns the configured {@code scope}, or {@code null} if unset.
     *
     * @return the query scope, or {@code null}
     */
    public QueryScope scope() {
        return scope;
    }

    /**
     * Returns the configured {@code markRead} flag, or {@code null} if unset.
     *
     * @return whether retrieved documents are marked as read, or {@code null}
     */
    public Boolean markRead() {
        return markRead;
    }

    /**
     * Returns the configured {@code markUnread} flag, or {@code null} if unset.
     *
     * @return whether retrieved documents are marked as unread, or {@code null}
     */
    public Boolean markUnread() {
        return markUnread;
    }

    /**
     * Returns the configured {@code includeEmptyRows} flag, or {@code null} if unset.
     *
     * @return whether empty rows are included, or {@code null}
     */
    public Boolean includeEmptyRows() {
        return includeEmptyRows;
    }

    /**
     * Returns the configured {@code start} offset, or {@code null} if unset.
     *
     * @return the zero-based index of the first entry to return, or {@code null}
     */
    public Integer start() {
        return start;
    }

    /**
     * Returns a list of {@link Parameter} objects representing the configured query parameters, using the parameter names defined
     * by the {@code fetchViewEntries} operation. Parameters left unset are omitted from the list, so the server defaults take
     * effect for them. The multi-valued parameters {@code category} and {@code key} contribute one entry per element, in order.
     *
     * @return a list of {@link Parameter} objects representing the configured query parameters
     */
    public List<Parameter> toParameterList() {
        List<Parameter> params = new ArrayList<>();

        if (mode != null) {
            params.add(new Parameter(PARAM_MODE, mode));
        }
        if (meta != null) {
            params.add(new Parameter(PARAM_META, meta.toString()));
        }
        if (startsWith != null) {
            params.add(new Parameter(PARAM_STARTS_WITH, startsWith));
        }
        if (metaAdditional != null) {
            params.add(new Parameter(PARAM_META_ADDITIONAL, metaAdditional.toString()));
        }
        if (category != null) {
            for (String value : category) {
                params.add(new Parameter(PARAM_CATEGORY, value));
            }
        }
        if (column != null) {
            params.add(new Parameter(PARAM_COLUMN, column));
        }
        if (distinctDocuments != null) {
            params.add(new Parameter(PARAM_DISTINCT_DOCUMENTS, distinctDocuments.toString()));
        }
        if (ftSearchQuery != null) {
            params.add(new Parameter(PARAM_FT_SEARCH_QUERY, ftSearchQuery));
        }
        if (count != null) {
            params.add(new Parameter(PARAM_COUNT, count.toString()));
        }
        if (startKey != null) {
            params.add(new Parameter(PARAM_START_KEY, startKey));
        }
        if (untilKey != null) {
            params.add(new Parameter(PARAM_UNTIL_KEY, untilKey));
        }
        if (unreadOnly != null) {
            params.add(new Parameter(PARAM_UNREAD_ONLY, unreadOnly.toString()));
        }
        if (keyAllowPartial != null) {
            params.add(new Parameter(PARAM_KEY_ALLOW_PARTIAL, keyAllowPartial.toString()));
        }
        if (documents != null) {
            params.add(new Parameter(PARAM_DOCUMENTS, documents.toString()));
        }
        if (direction != null) {
            params.add(new Parameter(PARAM_DIRECTION, direction.value()));
        }
        if (richTextAs != null) {
            params.add(new Parameter(PARAM_RICH_TEXT_AS, richTextAs.value()));
        }
        if (keyType != null) {
            params.add(new Parameter(PARAM_KEY_TYPE, keyType.value()));
        }
        if (key != null) {
            for (String value : key) {
                params.add(new Parameter(PARAM_KEY, value));
            }
        }
        if (scope != null) {
            params.add(new Parameter(PARAM_SCOPE, scope.value()));
        }
        if (markRead != null) {
            params.add(new Parameter(PARAM_MARK_READ, markRead.toString()));
        }
        if (markUnread != null) {
            params.add(new Parameter(PARAM_MARK_UNREAD, markUnread.toString()));
        }
        if (includeEmptyRows != null) {
            params.add(new Parameter(PARAM_INCLUDE_EMPTY_ROWS, includeEmptyRows.toString()));
        }
        if (start != null) {
            params.add(new Parameter(PARAM_START, start.toString()));
        }

        return params;
    }

}
