/*
 * Copyright (c) 2026 Serdar Basegmez
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openntf.drapi.http;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openntf.drapi.internal.http.UriBuilder;
import org.openntf.drapi.util.TypeUtils;

/**
 * Mutable builder for HCL Domino REST API URL paths.
 * <p>
 * Segments are collected in order; each one is trimmed of surrounding whitespace and slashes and then URL-encoded as it is added. The
 * {@link #toString()} rendering joins the collected segments with {@code /}, guarantees a single leading slash and strips any trailing
 * slash.
 * <p>
 * Instances are obtained through the static factory methods ({@link #root()}, {@link #empty()}, {@link #of(String)}) and extended in
 * place with {@link #append(String)}, which returns {@code this} so calls can be chained. This class is not thread-safe.
 *
 * <i>Javadoc comments are generated by Claude Code (Sonnet 5)</i>
 */
public class ApiPath {

    private final List<String> segments;

    private ApiPath() {
        this.segments = new ArrayList<>();
    }

    /**
     * Creates a path rooted at the Domino REST API base, {@code /api/v1}.
     *
     * @return a new {@code ApiPath} containing the {@code /api/v1} prefix
     */
    public static ApiPath root() {
        return of("/api/v1");
    }

    /**
     * Creates a path rooted at the API base {@code /api/v1} with the given segments appended.
     *
     * @param additionalSegments one or more slash-separated segments to add after {@code /api/v1}; a {@code null} or blank value adds
     *                           nothing
     * @return a new {@code ApiPath} starting with {@code /api/v1}
     */
    public static ApiPath root(String additionalSegments) {
        return root().append(additionalSegments);
    }

    /**
     * Creates an empty path that carries no segments.
     *
     * @return a new, empty {@code ApiPath}
     */
    public static ApiPath empty() {
        return new ApiPath();
    }

    /**
     * Creates a path from the given slash-separated segments.
     *
     * @param segments one or more slash-separated path segments; a {@code null} or blank value yields an empty path
     * @return a new {@code ApiPath} containing the parsed segments
     */
    public static ApiPath of(String segments) {
        return new ApiPath().append(segments);
    }

    /**
     * Splits the argument on {@code /} and appends each non-blank part as a separate segment, trimming surrounding whitespace and
     * slashes and URL-encoding the result. A {@code null} or blank argument is ignored.
     *
     * @param segment one or more slash-separated segments to add
     * @return this {@code ApiPath}, to allow chaining
     */
    public ApiPath append(String segment) {
        if (TypeUtils.isNotBlank(segment)) {
            Arrays.stream(segment.split("/")).forEach(part -> {
                if (TypeUtils.isNotBlank(part)) {
                    this.segments.add(normalizeAndEncodePath(part));
                }
            });
        }
        return this;
    }

    @Override
    public String toString() {
        String result = String.join("/", segments);

        if(!result.startsWith("/")) {
            result = "/" + result;
        }
        if(result.endsWith("/")) {
            result = result.substring(0, result.length() - 1);
        }

        return result;
    }


    private static String normalizeAndEncodePath(String path) {
        String trimmed = path.trim();

        int start = trimmed.startsWith("/") ? 1 : 0;
        int end = trimmed.endsWith("/") ? trimmed.length() - 1 : trimmed.length();

        return UriBuilder.urlEncode(trimmed.substring(start, end).trim());
    }

}
