# Base URL for the DRAPI service. This is the only required property.
BASEURL=https://my-drapi-service.com:8880

# Authentication information for the DRAPI service. This is optional and can be set if needed.
# These configuration properties are solely used for built-in PasswordTokenSource.
auth.UserName=Doctor Who
auth.Password=VeryComplicatedPassword42

# If omitted, the SDK will use the default scope (MAIL $DATA).
auth.scope=MAIL $DATA

# You can change the user agent string sent with requests to the DRAPI service. This is optional.
USERAGENT=your_user_agent

# You can change the connection timeout in seconds. This is optional. Default: 10
CONNECTTIMEOUTSECS=10

# You can change the request timeout in seconds. This is optional. Default: 15
REQUESTTIMEOUTSECS=15

