# Base URL for the DRAPI service. This is the only required property.
BASEURL=https://my-drapi-service.com:8880

# Authentication scope for the DRAPI service. This is optional and can be set if needed.
# If omitted, the SDK will use the default scope (MAIL $DATA).
AUTHSCOPE=MAIL $DATA

# This will set the authentication method to basic JWT authentication.
UserName=Doctor Who
Password=VeryComplicatedPassword42

# Alternatively you can supply Token for JWT authentication.
Token=your_token

# Alternatively you can supply a OAuth information for JWT authentication (Not implemented yet).
APPID=your_app_id
APPSECRET=your_app_secret

# You can change the user agent string sent with requests to the DRAPI service. This is optional.
USERAGENT=your_user_agent

# You can change the connection timeout in seconds. This is optional. Default: 10
CONNECTTIMEOUTSECS=10

# You can change the request timeout in seconds. This is optional. Default: 15
REQUESTTIMEOUTSECS=15

