/*
 * Copyright (c) 2026 Serdar Basegmez
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openntf.drapi.api;

import java.util.concurrent.CompletableFuture;
import org.openntf.drapi.api.options.DocumentsGetOptions;
import org.openntf.drapi.meta.Document;

/**
 * Access to the "document" resources of the HCL Domino REST API, scoped to a single data source. An instance is obtained from
 * {@link org.openntf.drapi.DrapiDataSource#documents()}, and every call is issued against the {@code dataSource} (scope) that the
 * originating {@link org.openntf.drapi.DrapiDataSource} represents.
 * <p>
 * <i>Javadoc auto-generated by Claude Code (Sonnet 5) based on HCL Domino Rest API - OpenApi specification 1.42.6</i>
 */
public interface DocumentsApi {

    /**
     * Retrieves a document by its universal id, applying the given query options.
     * <p>
     * Corresponds to the {@code getDocument} operation ({@code GET /document/{unid}}), described in the specification as
     * "retrieve a given document at its appropriate mode". The target scope is supplied automatically from the originating
     * {@link org.openntf.drapi.DrapiDataSource}.
     *
     * @param documentId the universal id (UNID) of the document to retrieve
     * @param options    the optional query parameters. {@link DocumentsGetOptions#create()} to use the server defaults
     * @return a future that completes with the requested {@link Document}, or completes exceptionally if the document cannot be
     *         retrieved, for example because it does not exist or access is denied
     */
    CompletableFuture<Document> get(String documentId, DocumentsGetOptions options);

    /**
     * Retrieves a document by its universal id, using the server defaults for every optional parameter.
     * <p>
     * Corresponds to the {@code getDocument} operation ({@code GET /document/{unid}}), described in the specification as
     * "retrieve a given document at its appropriate mode".
     *
     * @param documentId the universal id (UNID) of the document to retrieve
     * @return a future that completes with the requested {@link Document}, or completes exceptionally if the document cannot be
     *         retrieved, for example because it does not exist or access is denied
     */
    default CompletableFuture<Document> get(String documentId) {
        return get(documentId, DocumentsGetOptions.create());
    }

}
