/*
 * Copyright (c) 2026 Serdar Basegmez
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openntf.drapi.api;

import java.util.concurrent.CompletableFuture;
import java.util.stream.Stream;
import org.openntf.drapi.api.options.ListsGetOptions;
import org.openntf.drapi.meta.ListEntry;

/**
 * Access to the "list" resources (views and folders) of the HCL Domino REST API, scoped to a single data source. Every call is issued
 * against the {@code dataSource} (scope) of the originating {@link org.openntf.drapi.DrapiDataSource}.
 * <p>
 * <i>Javadoc auto-generated by Claude Code (Sonnet 5) based on HCL Domino Rest API - OpenApi specification 1.42.6</i>
 */
public interface ListsApi {

    // FIXME: Stream<ListEntry> is a lazy stream, but the underlying HTTP response is not closed until the stream is fully consumed.
    //  Consider using a different approach to ensure proper resource management.

    /**
     * Reads the entries of a view or folder, applying the given query options.
     * <p>
     * Corresponds to the {@code fetchViewEntries} operation ({@code GET /lists/{name}}), described in the specification as "pulls in
     * view data". Each returned {@link ListEntry} exposes its metadata (the {@code @}-prefixed properties such as {@code @unid},
     * {@code @noteid} and {@code @index}) separately from its column values. The operation reports a not-found error when no view or
     * folder with the given name is configured for the data source.
     * <p>
     * Remark: Returning stream is a lazy stream, but the underlying HTTP response is not closed until the stream is fully consumed. So
     * we need to change this approach in future versions to ensure proper resource management.
     *
     * @param viewName the name of the view or folder to read
     * @param options  the query parameters to apply; use {@link ListsGetOptions#create()} for an empty set
     * @return a future that completes with the view entries as a {@link Stream} of {@link ListEntry} values
     */
    CompletableFuture<Stream<ListEntry>> get(String viewName, ListsGetOptions options);


    /**
     * Reads the entries of a view or folder using the server defaults for every optional parameter. This is a shorthand for
     * {@link #get(String, ListsGetOptions) get(viewName, ListsGetOptions.create())}.
     * <p>
     * Remark: Returning stream is a lazy stream, but the underlying HTTP response is not closed until the stream is fully consumed. So
     * we need to change this approach in future versions to ensure proper resource management.
     *
     * @param viewName the name of the view or folder to read
     * @return a future that completes with the view entries as a {@link Stream} of {@link ListEntry} values
     */
    default CompletableFuture<Stream<ListEntry>> get(String viewName) {
        return get(viewName, ListsGetOptions.create());
    }

}
