<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.openntf.drapi</groupId>
        <artifactId>drapi-sdk-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>drapi-sdk-core</artifactId>
    <name>OpenNTF Java SDK for HCL Domino REST API :: Core</name>
    <description>Core features and dependencies for Domino REST API Java SDK</description>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <environmentVariables>
                        <!-- Test environment variables for DrapiConfigBuilder tests -->
                        <DRAPI_BASEURL>http://localhost:8089</DRAPI_BASEURL>
                        <DRAPI_TOKEN>some-token-value</DRAPI_TOKEN>
                    </environmentVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
